routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

Route::group(['middleware' => ['install']], function () {	

	Auth::routes();
	Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');

	Route::group(['middleware' => ['auth']], function () {
		
		Route::get('/dashboard', 'DashboardController@index');
		
		//Profile Controller
		Route::get('profile/my_profile', 'ProfileController@my_profile');
		Route::get('profile/edit', 'ProfileController@edit');
		Route::post('profile/update', 'ProfileController@update');
		Route::get('profile/change_password', 'ProfileController@change_password');
		Route::post('profile/update_password', 'ProfileController@update_password');
		
		//Extend Membertship
		Route::get('membership/extend', 'MembershipController@extend');
		
		//Payment Gateway PayPal
		Route::post('membership/pay','MembershipController@pay');	
		Route::get('membership/paypal/{action?}','MembershipController@paypal');		
		
		//Payment Gateway Stripe
		Route::post('membership/stripe_payment/{payment_id}','MembershipController@stripe_payment');	

		
		Route::group(['middleware' => ['admin']], function () {
			//User Controller
			Route::resource('users','UserController');
			Route::get('members/payment_history','UserController@payment_history');
			
			//Language Controller
			Route::resource('languages','LanguageController');	
			
			//Utility Controller
			Route::match(['get', 'post'],'administration/general_settings/{store?}', 'UtilityController@settings');
			Route::post('administration/upload_logo', 'UtilityController@upload_logo');
			Route::get('administration/backup_database', 'UtilityController@backup_database');
			
			//Email Template
			Route::resource('email_templates','EmailTemplateController');
			
		});
		
		Route::group(['middleware' => ['company']], function () {

			//Contact Group
			Route::resource('contact_groups','ContactGroupController');
		     
			//Contact Controller
			Route::get('contacts/get_table_data','ContactController@get_table_data');
			Route::post('contacts/send_email/{id}','ContactController@send_email')->name('contacts.send_email');
			Route::resource('contacts','ContactController');

			//Account Controller
			Route::resource('accounts','AccountController');
			

			//Income Controller
			Route::get('income/get_table_data','IncomeController@get_table_data');
			Route::get('income/calendar','IncomeController@calendar')->name('income.income_calendar');
			Route::resource('income','IncomeController');
			
			
			//Expense Controller
			Route::get('expense/get_table_data','ExpenseController@get_table_data');
			Route::get('expense/calendar','ExpenseController@calendar')->name('expense.expense_calendar');
			Route::resource('expense','ExpenseController');
			
			//Transfer Controller
			Route::get('transfer/create', 'TransferController@create')->name('transfer.create');
			Route::post('transfer/store', 'TransferController@store')->name('transfer.store');
			
			//Repeating Income
			Route::get('repeating_income/get_table_data','RepeatingIncomeController@get_table_data');
			Route::resource('repeating_income','RepeatingIncomeController');
			
			//Repeating Expense
			Route::get('repeating_expense/get_table_data','RepeatingExpenseController@get_table_data');
			Route::resource('repeating_expense','RepeatingExpenseController');

			//Chart Of Accounts
			Route::resource('chart_of_accounts','ChartOfAccountController');

			//Payment Method
			Route::resource('payment_methods','PaymentMethodController');
					
			//Supplier Controller
			Route::resource('suppliers','SupplierController');

			//Product Controller
			Route::get('products/get_product/{id}','ProductController@get_product');
			Route::resource('products','ProductController');

			//Product Controller
			Route::resource('services','ServiceController');

			//Purchase Order
			Route::get('purchase_orders/create_payment/{id}','PurchaseController@create_payment')->name('purchase_orders.create_payment');
			Route::post('purchase_orders/store_payment','PurchaseController@store_payment')->name('purchase_orders.create_payment');
			Route::get('purchase_orders/view_payment/{id}','PurchaseController@view_payment')->name('purchase_orders.view_payment');
			Route::get('purchase_orders/download_pdf/{id}','PurchaseController@download_pdf')->name('purchase_orders.download_pdf');
			Route::resource('purchase_orders','PurchaseController');

			//Purchase Return
			Route::resource('purchase_returns','PurchaseReturnController');
			
			//Sales Return
			Route::resource('sales_returns','SalesReturnController');
			
			
			//Invoice Controller
			Route::get('invoices/download_pdf/{id}','InvoiceController@download_pdf')->name('invoices.download_pdf');
			Route::get('invoices/create_payment/{id}','InvoiceController@create_payment')->name('invoices.create_payment');
			Route::post('invoices/store_payment','InvoiceController@store_payment')->name('invoices.create_payment');
			Route::get('invoices/view_payment/{id}','InvoiceController@view_payment')->name('invoices.view_payment');
			Route::get('invoices/create_email/{invoice_id}','InvoiceController@create_email')->name('invoices.send_email');
			Route::post('invoices/send_email','InvoiceController@send_email')->name('invoices.send_email');
			Route::resource('invoices','InvoiceController');

			//Quotation Controller
			Route::get('quotations/download_pdf/{id}','QuotationController@download_pdf')->name('quotations.download_pdf');
			Route::get('quotations/convert_invoice/{quotation_id}','QuotationController@convert_invoice')->name('quotations.convert_invoice');
			Route::get('quotations/create_email/{quotation_id}','QuotationController@create_email')->name('quotations.send_email');
			Route::post('quotations/send_email','QuotationController@send_email')->name('quotations.send_email');
			Route::resource('quotations','QuotationController');

			//Staff Controller
			Route::resource('staffs','StaffController');
			
			//Company Settings Controller
			Route::post('company/upload_logo', 'CompanySettingsController@upload_logo')->name('company.change_logo');
			Route::match(['get', 'post'],'company/general_settings/{store?}', 'CompanySettingsController@settings')->name('company.change_settings');
			
			//Company Email Template
			Route::get('company_email_template/get_template/{id}','CompanyEmailTemplateController@get_template');
			Route::resource('company_email_template','CompanyEmailTemplateController');
			
			//Tax Controller
			Route::resource('taxs','TaxController');
			
			//Product Unit Controller
			Route::resource('product_units','ProductUnitController');
			
			//Permission Controller
			Route::get('permission/control/{user_id?}', 'PermissionController@index')->name('permission.manage');
			Route::post('permission/store', 'PermissionController@store')->name('permission.manage');

			
			//Report Controller
			Route::match(['get', 'post'],'reports/account_statement/{view?}', 'ReportController@account_statement')->name('reports.account_statement');
			Route::match(['get', 'post'],'reports/day_wise_income/{view?}', 'ReportController@day_wise_income')->name('reports.day_wise_income');
			Route::match(['get', 'post'],'reports/date_wise_income/{view?}', 'ReportController@date_wise_income')->name('reports.date_wise_income');
			Route::match(['get', 'post'],'reports/day_wise_expense/{view?}', 'ReportController@day_wise_expense')->name('reports.day_wise_expense');
			Route::match(['get', 'post'],'reports/date_wise_expense/{view?}', 'ReportController@date_wise_expense')->name('reports.date_wise_expense');
			Route::match(['get', 'post'],'reports/transfer_report/{view?}', 'ReportController@transfer_report')->name('reports.transfer_report');
			Route::match(['get', 'post'],'reports/income_vs_expense/{view?}', 'ReportController@income_vs_expense')->name('reports.income_vs_expense');
			Route::match(['get', 'post'],'reports/report_by_payer/{view?}', 'ReportController@report_by_payer')->name('reports.report_by_payer');
			Route::match(['get', 'post'],'reports/report_by_payee/{view?}', 'ReportController@report_by_payee')->name('reports.report_by_payee');

		});
		
		Route::group(['middleware' => ['client']], function () {
		    Route::get('client/invoices/{status?}','ClientController@invoices');
		    Route::get('client/view_invoice/{id}','ClientController@view_invoice');
		    Route::post('client/make_payment/{id}','ClientController@make_payment');
		    Route::get('client/quotations','ClientController@quotations');
		    Route::get('client/view_quotation/{id}','ClientController@view_quotation');
		    Route::get('client/transactions','ClientController@transactions');
			Route::get('client/view_transaction/{id}','ClientController@view_transaction');
		    
			//PayPal Payment gateway
			Route::get('client/paypal/{action?}','ClientController@paypal');	
		});
		
	});
	
});

Route::get('/installation', 'Install\InstallController@index');
Route::get('install/database', 'Install\InstallController@database');
Route::post('install/process_install', 'Install\InstallController@process_install');
Route::get('install/create_user', 'Install\InstallController@create_user');
Route::post('install/store_user', 'Install\InstallController@store_user');
Route::get('install/system_settings', 'Install\InstallController@system_settings');
Route::post('install/finish', 'Install\InstallController@final_touch');		

//JSON data for dashboard chart
Route::get('dashboard/json_month_wise_income_expense','DashboardController@json_month_wise_income_expense')->middleware('auth');

app/Service.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Service extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'services';


    public function tax()
    {
        return $this->belongsTo('App\Tax',"tax_id")->withDefault();
    }
}

app/Http/Controllers/ServiceController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Service;
use App\Item;
use Validator;
use Illuminate\Validation\Rule;

class ServiceController extends Controller
{
	
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = Item::where("company_id",company_id())
		            ->where("item_type","service")
                    ->orderBy("id","desc")->get();
        return view('backend.accounting.service.list',compact('items'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
		if( ! $request->ajax()){
		   return view('backend.accounting.service.create');
		}else{
           return view('backend.accounting.service.modal.create');
		}
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {	
		$validator = Validator::make($request->all(), [
			'item_name' => 'required',
            'cost' => 'required|numeric',
            'tax_method' => 'required',
		]);
		
		if ($validator->fails()) {
			if($request->ajax()){ 
			    return response()->json(['result'=>'error','message'=>$validator->errors()->all()]);
			}else{
				return redirect('services/create')
							->withErrors($validator)
							->withInput();
			}			
		}
			
        //Create Item
        $item = new Item();
        $item->item_name = $request->input('item_name');
        $item->item_type = 'service';
        $item->company_id = company_id();
        $item->save();


	    //Create Product
        $service = new Service();
	    $service->item_id = $item->id;
        $service->cost = $request->input('cost');
        $service->tax_method = $request->input('tax_method');
        $service->tax_id = $request->input('tax_id');
        $service->description = $request->input('description');
        
        $service->save();
        
		if(! $request->ajax()){
           return redirect('services/create')->with('success', _lang('Information has been added sucessfully'));
        }else{
		   return response()->json(['result'=>'success','action'=>'store','message'=>_lang('Information has been added sucessfully'),'data'=>$service]);
		}
        
   }
	

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request,$id)
    {
        $item = Item::where("id",$id)->where("company_id",company_id())->first();

		if(! $request->ajax()){
		    return view('backend.accounting.service.view',compact('item','id'));
		}else{
			return view('backend.accounting.service.modal.view',compact('item','id'));
		} 
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request,$id)
    {
        $item = Item::where("id",$id)->where("company_id",company_id())->first();

		if(! $request->ajax()){
		   return view('backend.accounting.service.edit',compact('item','id'));
		}else{
           return view('backend.accounting.service.modal.edit',compact('item','id'));
		}  
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
			'item_name' => 'required',
            'cost' => 'required|numeric',
            'tax_method' => 'required',
		]);
		
		if ($validator->fails()) {
			if($request->ajax()){ 
			    return response()->json(['result'=>'error','message'=>$validator->errors()->all()]);
			}else{
				return redirect()->route('services.edit', $id)
							->withErrors($validator)
							->withInput();
			}			
		}
    
        //Update item
        $item = Item::where("id",$id)->where("company_id",company_id())->first();
        
        if( $item ){

            $item->item_name = $request->input('item_name');
            $item->item_type = 'service';
            $item->company_id = company_id();
            $item->save();

            
            $service = Service::where("item_id",$id)->first();
            $service->item_id = $item->id;
            $service->cost = $request->input('cost');
            $service->tax_method = $request->input('tax_method');
            $service->tax_id = $request->input('tax_id');
            $service->description = $request->input('description');
        
            $service->save();
        }else{
            if(! $request->ajax()){
                return redirect('services')->with('error', _lang('Update Failed !'));
             }else{
                return response()->json(['result'=>'error','message'=>_lang('Update Failed !')]);
             }
        }

		
		if(! $request->ajax()){
           return redirect('services')->with('success', _lang('Information has been updated sucessfully'));
        }else{
		   return response()->json(['result'=>'success','action'=>'update', 'message'=>_lang('Information has been updated sucessfully'),'data'=>$service]);
		}
	    
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $item = Item::where("id",$id)->where("company_id",company_id());
        $item->delete();

        $service = Service::where("item_id",$id);
        $service->delete();
        return redirect('services')->with('success',_lang('Information has been deleted sucessfully'));
    }
}

resources/views/backend/accounting/service/create.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
	<div class="col-md-12">
	<div class="panel panel-default">
	<div class="panel-heading panel-title">{{ _lang('Add Service') }}</div>

	<div class="panel-body">
		  <form method="post" class="validate" autocomplete="off" action="{{ url('services') }}" enctype="multipart/form-data">
			{{ csrf_field() }}
			
				<div class="col-md-6">
				  <div class="form-group">
					<label class="control-label">{{ _lang('Service Name') }}</label>						
					<input type="text" class="form-control" name="item_name" value="{{ old('item_name') }}">
				  </div>
				</div>

				<div class="col-md-6">
				  <div class="form-group">
					<label class="control-label">{{ _lang('Service Cost').' '.currency() }}</label>						
					<input type="text" class="form-control" name="cost" value="{{ old('cost') }}" required>
				  </div>
				</div>


				<div class="col-md-6">
				  <div class="form-group">
					<label class="control-label">{{ _lang('Tax Method') }}</label>						
					<select class="form-control" name="tax_method" required>
              <option value="exclusive">{{ _lang('Exclusive') }}</option>
              <option value="inclusive">{{ _lang('Inclusive') }}</option>
					</select>	
				  </div>
				</div>

				<div class="col-md-6">
				  <div class="form-group">
					<label class="control-label">{{ _lang('Tax') }}</label>						
					<select class="form-control select2" name="tax_id">
							<option value="">{{ _lang('No Tax') }}</option>
							@foreach(App\Tax::where("company_id",company_id())->get() as $tax)
								 <option value="{{ $tax->id }}">{{ $tax->tax_name }} - {{ $tax->type =='percent' ? $tax->rate.' %' : $tax->rate }}</option>
							@endforeach
					 </select>
				  </div>
				</div>

				<div class="col-md-6">
				  <div class="form-group">
					<label class="control-label">{{ _lang('Description') }}</label>						
					<textarea class="form-control" name="description">{{ old('description') }}</textarea>
				  </div>
				</div>

				
			<div class="form-group">
			  <div class="col-md-12">
				<button type="reset" class="btn btn-danger">{{ _lang('Reset') }}</button>
				<button type="submit" class="btn btn-primary">{{ _lang('Save') }}</button>
			  </div>
			</div>
		</form>
	</div>
  </div>
 </div>
</div>
@endsection

resources/views/backend/accounting/service/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading panel-title">{{ _lang('Update Servuce') }}</div>

			<div class="panel-body">
				<form method="post" class="validate" autocomplete="off" action="{{action('ServiceController@update', $id)}}" enctype="multipart/form-data">
					{{ csrf_field()}}
					<input name="_method" type="hidden" value="PATCH">				

					<div class="col-md-6">
					<div class="form-group">
						<label class="control-label">{{ _lang('Service Name') }}</label>						
						<input type="text" class="form-control" name="item_name" value="{{ $item->item_name }}">
					</div>
					</div>


					<div class="col-md-6">
					<div class="form-group">
						<label class="control-label">{{ _lang('Service Cost').' '.currency() }}</label>						
						<input type="text" class="form-control" name="cost" value="{{ $item->service->cost }}" required>
					</div>
					</div>


					<div class="col-md-6">
					<div class="form-group">
						<label class="control-label">{{ _lang('Tax Method') }}</label>						
						<select class="form-control" name="tax_method" required>
							<option value="exclusive" {{ $item->service->tax_method == 'exclusive' ? 'selected' : '' }}>{{ _lang('Exclusive') }}</option>
							<option value="inclusive" {{ $item->service->tax_method == 'inclusive' ? 'selected' : '' }}>{{ _lang('Inclusive') }}</option>
						</select>	
					</div>
					</div>

					<div class="col-md-6">
					<div class="form-group">
						<label class="control-label">{{ _lang('Tax') }}</label>						
						<select class="form-control select2" name="tax_id">
							<option value="">{{ _lang('Select One') }}</option>
							@foreach(App\Tax::where("company_id",company_id())->get() as $tax)
								<option value="{{ $tax->id }}" {{ $item->service->tax_id==$tax->id ? 'selected' : '' }}>{{ $tax->tax_name }} - {{ $tax->type =='percent' ? $tax->rate.' %' : $tax->rate }}</option>
							@endforeach
						</select>
					</div>
					</div>

					<div class="col-md-6">
					<div class="form-group">
						<label class="control-label">{{ _lang('Description') }}</label>						
						<textarea class="form-control" name="description">{{ $item->service->description }}</textarea>
					</div>
					</div>
	
					<div class="form-group">
					  <div class="col-md-12">
						<button type="submit" class="btn btn-primary">{{ _lang('Update') }}</button>
					  </div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

@endsection

resources/views/backend/accounting/service/list.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default no-export">
			<div class="panel-heading"><span class="panel-title">{{ _lang('List Service') }}</span>
			<a class="btn btn-primary btn-sm pull-right ajax-modal" data-title="{{ _lang('Add New Service') }}" href="{{ route('services.create') }}">{{ _lang('Add New') }}</a>
			</div>

			<div class="panel-body">
			 @if (\Session::has('success'))
			  <div class="alert alert-success">
				<p>{{ \Session::get('success') }}</p>
			  </div>
			  <br />
			 @endif
			<table class="table table-bordered data-table">
			<thead>
			  <tr>
					<th>{{ _lang('Service') }}</th>
					<th>{{ _lang('Cost') }}</th>
					<th>{{ _lang('Tax Method') }}</th>
					<th class="text-center">{{ _lang('Action') }}</th>
			  </tr>
			</thead>
			<tbody>
				
				@php $currency = currency(); @endphp
			  @foreach($items as $item)
			  <tr id="row_{{ $item->id }}">
					<td class='item_id'>{{ $item->item_name }}</td>
					<td class='cost'>{{ $currency.' '.$item->service->cost }}</td>
					<td class='tax_method'>{{ ucwords($item->service->tax_method) }}</td>
					<td class="text-center">
						<form action="{{action('ServiceController@destroy', $item['id'])}}" method="post">
						<a href="{{action('ServiceController@edit', $item['id'])}}" data-title="{{ _lang('Update Service') }}" class="btn btn-warning btn-sm ajax-modal">{{ _lang('Edit') }}</a>
						<a href="{{action('ServiceController@show', $item['id'])}}" data-title="{{ _lang('View Service') }}" class="btn btn-info btn-sm ajax-modal">{{ _lang('View') }}</a>
						{{ csrf_field() }}
						<input name="_method" type="hidden" value="DELETE">
						<button class="btn btn-danger btn-sm btn-remove" type="submit">{{ _lang('Delete') }}</button>
						</form>
					</td>
			  </tr>
			  @endforeach
			</tbody>
		  </table>
			</div>
		</div>
	</div>
</div>

@endsection

resources/views/backend/accounting/service/view.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
	<div class="col-md-12">
	<div class="panel panel-default">
	<div class="panel-heading">{{ _lang('View Product') }}</div>

	<div class="panel-body">
	  <table class="table table-bordered">
			<tr><td>{{ _lang('Item Id') }}</td><td>{{ $item->id }}</td></tr>
			<tr><td>{{ _lang('Service Name') }}</td><td>{{ $item->item_name }}</td></tr>
			<tr><td>{{ _lang('Service Cost') }}</td><td>{{ currency()." ".$item->service->product_cost }}</td></tr>
			<tr><td>{{ _lang('Tax Method') }}</td><td>{{ ucwords($item->service->tax_method) }}</td></tr>
			<tr><td>{{ _lang('Tax') }}</td><td>{{ isset($item->service->tax) ? $item->service->tax->tax_name : '' }}</td></tr>
			<tr><td>{{ _lang('Description') }}</td><td>{{ $item->service->description }}</td></tr>	
	  </table>
	</div>
  </div>
 </div>
</div>
@endsection