routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

Route::group(['middleware' => ['install']], function () {	

	Auth::routes();
	Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');

	Route::group(['middleware' => ['auth']], function () {
		
		Route::get('/dashboard', 'DashboardController@index');
		
		//Profile Controller
		Route::get('profile/my_profile', 'ProfileController@my_profile');
		Route::get('profile/edit', 'ProfileController@edit');
		Route::post('profile/update', 'ProfileController@update');
		Route::get('profile/change_password', 'ProfileController@change_password');
		Route::post('profile/update_password', 'ProfileController@update_password');
		
		//Extend Membertship
		Route::get('membership/extend', 'MembershipController@extend');
		
		//Payment Gateway PayPal
		Route::post('membership/pay','MembershipController@pay');	
		Route::get('membership/paypal/{action?}','MembershipController@paypal');		
		
		//Payment Gateway Stripe
		Route::post('membership/stripe_payment/{payment_id}','MembershipController@stripe_payment');	

		
		Route::group(['middleware' => ['admin']], function () {
			//User Controller
			Route::resource('users','UserController');
			Route::get('members/payment_history','UserController@payment_history');
			
			//Language Controller
			Route::resource('languages','LanguageController');	
			
			//Utility Controller
			Route::match(['get', 'post'],'administration/general_settings/{store?}', 'UtilityController@settings');
			Route::post('administration/upload_logo', 'UtilityController@upload_logo');
			Route::get('administration/backup_database', 'UtilityController@backup_database');
			
			//Email Template
			Route::resource('email_templates','EmailTemplateController');
			
		});
		
		Route::group(['middleware' => ['company']], function () {

			//Contact Group
			Route::resource('contact_groups','ContactGroupController');
		     
			//Contact Controller
			Route::get('contacts/get_table_data','ContactController@get_table_data');
			Route::post('contacts/send_email/{id}','ContactController@send_email')->name('contacts.send_email');
			Route::resource('contacts','ContactController');

			//Account Controller
			Route::resource('accounts','AccountController');
			

			//Income Controller
			Route::get('income/get_table_data','IncomeController@get_table_data');
			Route::get('income/calendar','IncomeController@calendar')->name('income.income_calendar');
			Route::resource('income','IncomeController');
			
			
			//Expense Controller
			Route::get('expense/get_table_data','ExpenseController@get_table_data');
			Route::get('expense/calendar','ExpenseController@calendar')->name('expense.expense_calendar');
			Route::resource('expense','ExpenseController');
			
			//Transfer Controller
			Route::get('transfer/create', 'TransferController@create')->name('transfer.create');
			Route::post('transfer/store', 'TransferController@store')->name('transfer.store');
			
			//Repeating Income
			Route::get('repeating_income/get_table_data','RepeatingIncomeController@get_table_data');
			Route::resource('repeating_income','RepeatingIncomeController');
			
			//Repeating Expense
			Route::get('repeating_expense/get_table_data','RepeatingExpenseController@get_table_data');
			Route::resource('repeating_expense','RepeatingExpenseController');

			//Chart Of Accounts
			Route::resource('chart_of_accounts','ChartOfAccountController');

			//Payment Method
			Route::resource('payment_methods','PaymentMethodController');
					
			//Supplier Controller
			Route::resource('suppliers','SupplierController');

			//Product Controller
			Route::get('products/get_product/{id}','ProductController@get_product');
			Route::resource('products','ProductController');

			//Product Controller
			Route::resource('services','ServiceController');

			//Purchase Order
			Route::get('purchase_orders/create_payment/{id}','PurchaseController@create_payment')->name('purchase_orders.create_payment');
			Route::post('purchase_orders/store_payment','PurchaseController@store_payment')->name('purchase_orders.create_payment');
			Route::get('purchase_orders/view_payment/{id}','PurchaseController@view_payment')->name('purchase_orders.view_payment');
			Route::get('purchase_orders/download_pdf/{id}','PurchaseController@download_pdf')->name('purchase_orders.download_pdf');
			Route::resource('purchase_orders','PurchaseController');

			//Purchase Return
			Route::resource('purchase_returns','PurchaseReturnController');
			
			//Sales Return
			Route::resource('sales_returns','SalesReturnController');
			
			
			//Invoice Controller
			Route::get('invoices/download_pdf/{id}','InvoiceController@download_pdf')->name('invoices.download_pdf');
			Route::get('invoices/create_payment/{id}','InvoiceController@create_payment')->name('invoices.create_payment');
			Route::post('invoices/store_payment','InvoiceController@store_payment')->name('invoices.create_payment');
			Route::get('invoices/view_payment/{id}','InvoiceController@view_payment')->name('invoices.view_payment');
			Route::get('invoices/create_email/{invoice_id}','InvoiceController@create_email')->name('invoices.send_email');
			Route::post('invoices/send_email','InvoiceController@send_email')->name('invoices.send_email');
			Route::resource('invoices','InvoiceController');

			//Quotation Controller
			Route::get('quotations/download_pdf/{id}','QuotationController@download_pdf')->name('quotations.download_pdf');
			Route::get('quotations/convert_invoice/{quotation_id}','QuotationController@convert_invoice')->name('quotations.convert_invoice');
			Route::get('quotations/create_email/{quotation_id}','QuotationController@create_email')->name('quotations.send_email');
			Route::post('quotations/send_email','QuotationController@send_email')->name('quotations.send_email');
			Route::resource('quotations','QuotationController');

			//Staff Controller
			Route::resource('staffs','StaffController');
			
			//Company Settings Controller
			Route::post('company/upload_logo', 'CompanySettingsController@upload_logo')->name('company.change_logo');
			Route::match(['get', 'post'],'company/general_settings/{store?}', 'CompanySettingsController@settings')->name('company.change_settings');
			
			//Company Email Template
			Route::get('company_email_template/get_template/{id}','CompanyEmailTemplateController@get_template');
			Route::resource('company_email_template','CompanyEmailTemplateController');
			
			//Tax Controller
			Route::resource('taxs','TaxController');
			
			//Product Unit Controller
			Route::resource('product_units','ProductUnitController');
			
			//Permission Controller
			Route::get('permission/control/{user_id?}', 'PermissionController@index')->name('permission.manage');
			Route::post('permission/store', 'PermissionController@store')->name('permission.manage');

			
			//Report Controller
			Route::match(['get', 'post'],'reports/account_statement/{view?}', 'ReportController@account_statement')->name('reports.account_statement');
			Route::match(['get', 'post'],'reports/day_wise_income/{view?}', 'ReportController@day_wise_income')->name('reports.day_wise_income');
			Route::match(['get', 'post'],'reports/date_wise_income/{view?}', 'ReportController@date_wise_income')->name('reports.date_wise_income');
			Route::match(['get', 'post'],'reports/day_wise_expense/{view?}', 'ReportController@day_wise_expense')->name('reports.day_wise_expense');
			Route::match(['get', 'post'],'reports/date_wise_expense/{view?}', 'ReportController@date_wise_expense')->name('reports.date_wise_expense');
			Route::match(['get', 'post'],'reports/transfer_report/{view?}', 'ReportController@transfer_report')->name('reports.transfer_report');
			Route::match(['get', 'post'],'reports/income_vs_expense/{view?}', 'ReportController@income_vs_expense')->name('reports.income_vs_expense');
			Route::match(['get', 'post'],'reports/report_by_payer/{view?}', 'ReportController@report_by_payer')->name('reports.report_by_payer');
			Route::match(['get', 'post'],'reports/report_by_payee/{view?}', 'ReportController@report_by_payee')->name('reports.report_by_payee');

		});
		
		Route::group(['middleware' => ['client']], function () {
		    Route::get('client/invoices/{status?}','ClientController@invoices');
		    Route::get('client/view_invoice/{id}','ClientController@view_invoice');
		    Route::post('client/make_payment/{id}','ClientController@make_payment');
		    Route::get('client/quotations','ClientController@quotations');
		    Route::get('client/view_quotation/{id}','ClientController@view_quotation');
		    Route::get('client/transactions','ClientController@transactions');
			Route::get('client/view_transaction/{id}','ClientController@view_transaction');
		    
			//PayPal Payment gateway
			Route::get('client/paypal/{action?}','ClientController@paypal');	
		});
		
	});
	
});

Route::get('/installation', 'Install\InstallController@index');
Route::get('install/database', 'Install\InstallController@database');
Route::post('install/process_install', 'Install\InstallController@process_install');
Route::get('install/create_user', 'Install\InstallController@create_user');
Route::post('install/store_user', 'Install\InstallController@store_user');
Route::get('install/system_settings', 'Install\InstallController@system_settings');
Route::post('install/finish', 'Install\InstallController@final_touch');		

//JSON data for dashboard chart
Route::get('dashboard/json_month_wise_income_expense','DashboardController@json_month_wise_income_expense')->middleware('auth');

resources/views/backend/accounting/income/modal/create.blade.php
<form method="post" class="ajax-submit" autocomplete="off" action="{{route('income.store')}}" enctype="multipart/form-data">
{{ csrf_field() }}
	
	<div class="col-md-6">
	  <div class="form-group">
		<label class="control-label">{{ _lang('Date') }}</label>						
		<input type="text" class="form-control datepicker" name="trans_date" value="{{ old('trans_date') }}" required>
	  </div>
	</div>

	<div class="col-md-6">
	  <div class="form-group">
		<label class="control-label">{{ _lang('Account') }}</label>						
		<select class="form-control select2" name="account_id" required>
		   <option value="">{{ _lang('Select One') }}</option>
		   {{ create_option("accounts","id","account_title",old('account_id'),array("company_id="=>company_id())) }}
		</select>
	  </div>
	</div>

	<div class="col-md-6">
	  <div class="form-group">
		<label class="control-label">{{ _lang('Income Type') }}</label>						
		<select class="form-control select2" name="chart_id" required>
		   <option value="">{{ _lang('Select One') }}</option>
		   {{ create_option("chart_of_accounts","id","name",old('chart_id'),array("type="=>"income","AND company_id="=>company_id())) }}
		</select>
	  </div>
	</div>

	<div class="col-md-6">
	  <div class="form-group">
		<label class="control-label">{{ _lang('Amount')." ".currency() }}</label>						
		<input type="text" class="form-control float-field" name="amount" value="{{ old('amount') }}" required>
	  </div>
	</div>

	<div class="col-md-6">
	  <div class="form-group">
		<label class="control-label">{{ _lang('Payer') }}</label>						
		<select class="form-control select2" name="payer_payee_id">
		   <option value="">{{ _lang('Select One') }}</option>
		   {{ create_option("contacts","id","contact_name",old('payer_payee_id'),array("company_id="=>company_id())) }}
		</select>
	  </div>
	</div>

	<div class="col-md-6">
	  <div class="form-group">
		<label class="control-label">{{ _lang('Payment Method') }}</label>						
		<select class="form-control select2" name="payment_method_id" required>
		   <option value="">{{ _lang('Select One') }}</option>
		   {{ create_option("payment_methods","id","name",old('payment_method_id'),array("company_id="=>company_id())) }}
		</select>
	  </div>
	</div>

	<div class="col-md-12">
	  <div class="form-group">
		<label class="control-label">{{ _lang('Reference') }}</label>						
		<input type="text" class="form-control" name="reference" value="{{ old('reference') }}">
	  </div>
	</div>

	<div class="col-md-12">
		<div class="form-group">
		<label class="control-label">{{ _lang('Attachment') }}</label>						
		<input type="file" class="form-control dropify" name="attachment">
		</div>
	</div>

	<div class="col-md-12">
	  <div class="form-group">
		<label class="control-label">{{ _lang('Note') }}</label>						
		<textarea class="form-control" name="note">{{ old('note') }}</textarea>
	  </div>
	</div>

	<div class="form-group">
	  <div class="col-md-12">
		<button type="reset" class="btn btn-danger">{{ _lang('Reset') }}</button>
		<button type="submit" class="btn btn-primary">{{ _lang('Save') }}</button>
	  </div>
	</div>
</form>

resources/views/backend/accounting/income/modal/edit.blade.php
<form method="post" class="ajax-submit" autocomplete="off" action="{{action('IncomeController@update', $id)}}" enctype="multipart/form-data">
	{{ csrf_field()}}
	<input name="_method" type="hidden" value="PATCH">				
	
	<div class="col-md-6">
	 <div class="form-group">
		<label class="control-label">{{ _lang('Date') }}</label>						
		<input type="text" class="form-control datepicker" name="trans_date" value="{{ $transaction->trans_date }}" required>
	 </div>
	</div>

	<div class="col-md-6">
	  <div class="form-group">
		<label class="control-label">{{ _lang('Account') }}</label>						
		<select class="form-control select2" name="account_id" required>
		   <option value="">{{ _lang('Select One') }}</option>
		   {{ create_option("accounts","id","account_title",$transaction->account_id,array("company_id="=>company_id())) }}
		</select>
	  </div>
	</div>

	<div class="col-md-6">
	  <div class="form-group">
		<label class="control-label">{{ _lang('Income Type') }}</label>						
		<select class="form-control select2" name="chart_id" required>
		   <option value="">{{ _lang('Select One') }}</option>
		   {{ create_option("chart_of_accounts","id","name",$transaction->chart_id,array("type="=>"income","AND company_id="=>company_id())) }}
		</select>
	  </div>
	</div>

	<div class="col-md-6">
	 <div class="form-group">
		<label class="control-label">{{ _lang('Amount')." ".currency() }}</label>						
		<input type="text" class="form-control float-field" name="amount" value="{{ $transaction->amount }}" required>
	 </div>
	</div>

	<div class="col-md-6">
	  <div class="form-group">
		<label class="control-label">{{ _lang('Payer') }}</label>						
		<select class="form-control select2" name="payer_payee_id">
			 <option value="">{{ _lang('Select One') }}</option>
			 {{ create_option("contacts","id","contact_name",$transaction->payer_payee_id,array("company_id="=>company_id())) }}
		</select>
	  </div>
	</div>

	<div class="col-md-6">
	  <div class="form-group">
		<label class="control-label">{{ _lang('Payment Method') }}</label>						
		<select class="form-control select2" name="payment_method_id" required>
		   <option value="">{{ _lang('Select One') }}</option>
		   {{ create_option("payment_methods","id","name",$transaction->payment_method_id,array("company_id="=>company_id())) }}
		</select>
	  </div>
	</div>

	<div class="col-md-12">
	 <div class="form-group">
		<label class="control-label">{{ _lang('Reference') }}</label>						
		<input type="text" class="form-control" name="reference" value="{{ $transaction->reference }}">
	 </div>
	</div>

	<div class="col-md-12">
		<div class="form-group">
		<label class="control-label">{{ _lang('Attachment') }}</label>						
		<input type="file" class="form-control dropify" name="attachment" data-default-file="{{ $transaction->attachment != "" ? asset('public/uploads/transactions/'.$transaction->attachment) : "" }}">
		</div>
	</div>

	<div class="col-md-12">
	 <div class="form-group">
		<label class="control-label">{{ _lang('Note') }}</label>						
		<textarea class="form-control" name="note">{{ $transaction->note }}</textarea>
	 </div>
	</div>

	<div class="form-group">
	  <div class="col-md-12">
		<button type="submit" class="btn btn-primary">{{ _lang('Update') }}</button>
	  </div>
	</div>
</form>

resources/views/backend/accounting/income/modal/view.blade.php
<div class="panel panel-default">
<div class="panel-body">
  <table class="table table-bordered">
	<tr><td>{{ _lang('Trans Date') }}</td><td>{{ date("d M, Y",strtotime($transaction->trans_date)) }}</td></tr>
	<tr><td>{{ _lang('Account') }}</td><td>{{ $transaction->account->account_title }}</td></tr>
	<tr><td>{{ _lang('Income Type') }}</td><td>{{ isset($transaction->income_type->name) ? $transaction->income_type->name : _lang('Transfer') }}</td></tr>
	<tr><td>{{ _lang('Amount') }}</td><td>{{ currency()." ".$transaction->amount }}</td></tr>
	<tr><td>{{ _lang('Payer') }}</td><td>{{ isset($transaction->payer->name) ? $transaction->payer->name : '' }}</td></tr>
	<tr><td>{{ _lang('Payment Method') }}</td><td>{{ $transaction->payment_method->name }}</td></tr>
	<tr><td>{{ _lang('Reference') }}</td><td>{{ $transaction->reference }}</td></tr>
	<tr>
		<td>{{ _lang('Attachment') }}</td>
			<td>
			  @if($transaction->attachment != "")
			   <a href="{{ asset('public/uploads/transactions/'.$transaction->attachment) }}" target="_blank" class="btn btn-primary btn-sm">{{ _lang('View Attachment') }}</a>
			  @else
				  <label class="label label-warning">
					<strong>{{ _lang('No Atachment Available !') }}</strong>
				  </label>
			  @endif
			</td>
		</tr>
	<tr><td>{{ _lang('Note') }}</td><td>{{ $transaction->note }}</td></tr>
  </table>
</div>
</div>