routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

Route::group(['middleware' => ['install']], function () {	

	Auth::routes();
	Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');

	Route::group(['middleware' => ['auth']], function () {
		
		Route::get('/dashboard', 'DashboardController@index');
		
		//Profile Controller
		Route::get('profile/my_profile', 'ProfileController@my_profile');
		Route::get('profile/edit', 'ProfileController@edit');
		Route::post('profile/update', 'ProfileController@update');
		Route::get('profile/change_password', 'ProfileController@change_password');
		Route::post('profile/update_password', 'ProfileController@update_password');
		
		//Extend Membertship
		Route::get('membership/extend', 'MembershipController@extend');
		
		//Payment Gateway PayPal
		Route::post('membership/pay','MembershipController@pay');	
		Route::get('membership/paypal/{action?}','MembershipController@paypal');		
		
		//Payment Gateway Stripe
		Route::post('membership/stripe_payment/{payment_id}','MembershipController@stripe_payment');	

		
		Route::group(['middleware' => ['admin']], function () {
			//User Controller
			Route::resource('users','UserController');
			Route::get('members/payment_history','UserController@payment_history');
			
			//Language Controller
			Route::resource('languages','LanguageController');	
			
			//Utility Controller
			Route::match(['get', 'post'],'administration/general_settings/{store?}', 'UtilityController@settings');
			Route::post('administration/upload_logo', 'UtilityController@upload_logo');
			Route::get('administration/backup_database', 'UtilityController@backup_database');
			
			//Email Template
			Route::resource('email_templates','EmailTemplateController');
			
		});
		
		Route::group(['middleware' => ['company']], function () {

			//Contact Group
			Route::resource('contact_groups','ContactGroupController');
		     
			//Contact Controller
			Route::get('contacts/get_table_data','ContactController@get_table_data');
			Route::post('contacts/send_email/{id}','ContactController@send_email')->name('contacts.send_email');
			Route::resource('contacts','ContactController');

			//Account Controller
			Route::resource('accounts','AccountController');
			

			//Income Controller
			Route::get('income/get_table_data','IncomeController@get_table_data');
			Route::get('income/calendar','IncomeController@calendar')->name('income.income_calendar');
			Route::resource('income','IncomeController');
			
			
			//Expense Controller
			Route::get('expense/get_table_data','ExpenseController@get_table_data');
			Route::get('expense/calendar','ExpenseController@calendar')->name('expense.expense_calendar');
			Route::resource('expense','ExpenseController');
			
			//Transfer Controller
			Route::get('transfer/create', 'TransferController@create')->name('transfer.create');
			Route::post('transfer/store', 'TransferController@store')->name('transfer.store');
			
			//Repeating Income
			Route::get('repeating_income/get_table_data','RepeatingIncomeController@get_table_data');
			Route::resource('repeating_income','RepeatingIncomeController');
			
			//Repeating Expense
			Route::get('repeating_expense/get_table_data','RepeatingExpenseController@get_table_data');
			Route::resource('repeating_expense','RepeatingExpenseController');

			//Chart Of Accounts
			Route::resource('chart_of_accounts','ChartOfAccountController');

			//Payment Method
			Route::resource('payment_methods','PaymentMethodController');
					
			//Supplier Controller
			Route::resource('suppliers','SupplierController');

			//Product Controller
			Route::get('products/get_product/{id}','ProductController@get_product');
			Route::resource('products','ProductController');

			//Product Controller
			Route::resource('services','ServiceController');

			//Purchase Order
			Route::get('purchase_orders/create_payment/{id}','PurchaseController@create_payment')->name('purchase_orders.create_payment');
			Route::post('purchase_orders/store_payment','PurchaseController@store_payment')->name('purchase_orders.create_payment');
			Route::get('purchase_orders/view_payment/{id}','PurchaseController@view_payment')->name('purchase_orders.view_payment');
			Route::get('purchase_orders/download_pdf/{id}','PurchaseController@download_pdf')->name('purchase_orders.download_pdf');
			Route::resource('purchase_orders','PurchaseController');

			//Purchase Return
			Route::resource('purchase_returns','PurchaseReturnController');
			
			//Sales Return
			Route::resource('sales_returns','SalesReturnController');
			
			
			//Invoice Controller
			Route::get('invoices/download_pdf/{id}','InvoiceController@download_pdf')->name('invoices.download_pdf');
			Route::get('invoices/create_payment/{id}','InvoiceController@create_payment')->name('invoices.create_payment');
			Route::post('invoices/store_payment','InvoiceController@store_payment')->name('invoices.create_payment');
			Route::get('invoices/view_payment/{id}','InvoiceController@view_payment')->name('invoices.view_payment');
			Route::get('invoices/create_email/{invoice_id}','InvoiceController@create_email')->name('invoices.send_email');
			Route::post('invoices/send_email','InvoiceController@send_email')->name('invoices.send_email');
			Route::resource('invoices','InvoiceController');

			//Quotation Controller
			Route::get('quotations/download_pdf/{id}','QuotationController@download_pdf')->name('quotations.download_pdf');
			Route::get('quotations/convert_invoice/{quotation_id}','QuotationController@convert_invoice')->name('quotations.convert_invoice');
			Route::get('quotations/create_email/{quotation_id}','QuotationController@create_email')->name('quotations.send_email');
			Route::post('quotations/send_email','QuotationController@send_email')->name('quotations.send_email');
			Route::resource('quotations','QuotationController');

			//Staff Controller
			Route::resource('staffs','StaffController');
			
			//Company Settings Controller
			Route::post('company/upload_logo', 'CompanySettingsController@upload_logo')->name('company.change_logo');
			Route::match(['get', 'post'],'company/general_settings/{store?}', 'CompanySettingsController@settings')->name('company.change_settings');
			
			//Company Email Template
			Route::get('company_email_template/get_template/{id}','CompanyEmailTemplateController@get_template');
			Route::resource('company_email_template','CompanyEmailTemplateController');
			
			//Tax Controller
			Route::resource('taxs','TaxController');
			
			//Product Unit Controller
			Route::resource('product_units','ProductUnitController');
			
			//Permission Controller
			Route::get('permission/control/{user_id?}', 'PermissionController@index')->name('permission.manage');
			Route::post('permission/store', 'PermissionController@store')->name('permission.manage');

			
			//Report Controller
			Route::match(['get', 'post'],'reports/account_statement/{view?}', 'ReportController@account_statement')->name('reports.account_statement');
			Route::match(['get', 'post'],'reports/day_wise_income/{view?}', 'ReportController@day_wise_income')->name('reports.day_wise_income');
			Route::match(['get', 'post'],'reports/date_wise_income/{view?}', 'ReportController@date_wise_income')->name('reports.date_wise_income');
			Route::match(['get', 'post'],'reports/day_wise_expense/{view?}', 'ReportController@day_wise_expense')->name('reports.day_wise_expense');
			Route::match(['get', 'post'],'reports/date_wise_expense/{view?}', 'ReportController@date_wise_expense')->name('reports.date_wise_expense');
			Route::match(['get', 'post'],'reports/transfer_report/{view?}', 'ReportController@transfer_report')->name('reports.transfer_report');
			Route::match(['get', 'post'],'reports/income_vs_expense/{view?}', 'ReportController@income_vs_expense')->name('reports.income_vs_expense');
			Route::match(['get', 'post'],'reports/report_by_payer/{view?}', 'ReportController@report_by_payer')->name('reports.report_by_payer');
			Route::match(['get', 'post'],'reports/report_by_payee/{view?}', 'ReportController@report_by_payee')->name('reports.report_by_payee');

		});
		
		Route::group(['middleware' => ['client']], function () {
		    Route::get('client/invoices/{status?}','ClientController@invoices');
		    Route::get('client/view_invoice/{id}','ClientController@view_invoice');
		    Route::post('client/make_payment/{id}','ClientController@make_payment');
		    Route::get('client/quotations','ClientController@quotations');
		    Route::get('client/view_quotation/{id}','ClientController@view_quotation');
		    Route::get('client/transactions','ClientController@transactions');
			Route::get('client/view_transaction/{id}','ClientController@view_transaction');
		    
			//PayPal Payment gateway
			Route::get('client/paypal/{action?}','ClientController@paypal');	
		});
		
	});
	
});

Route::get('/installation', 'Install\InstallController@index');
Route::get('install/database', 'Install\InstallController@database');
Route::post('install/process_install', 'Install\InstallController@process_install');
Route::get('install/create_user', 'Install\InstallController@create_user');
Route::post('install/store_user', 'Install\InstallController@store_user');
Route::get('install/system_settings', 'Install\InstallController@system_settings');
Route::post('install/finish', 'Install\InstallController@final_touch');		

//JSON data for dashboard chart
Route::get('dashboard/json_month_wise_income_expense','DashboardController@json_month_wise_income_expense')->middleware('auth');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Laravel\Passport\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'user_type', 'status', 'valid_to', 'profile_picture', 'currency'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
	
	public function client(){
		return $this->hasOne('App\Contact','user_id')->withDefault();
	}
	
}

app/Http/Controllers/API/UserController.php
<?php

namespace App\Http\Controllers\API;
use Illuminate\Http\Request; 
use App\Http\Controllers\Controller; 
use App\User; 
use Illuminate\Support\Facades\Auth; 
use Validator;
use Hash;


class UserController extends Controller 
{
	public $successStatus = 200;
	
	/** 
     * login api 
     * 
     * @return \Illuminate\Http\Response 
     */ 
    public function login(){ 
        if(Auth::attempt(['email' => request('email'), 'password' => request('password')])){ 
            $user = Auth::user(); 
            $success['token'] =  $user->createToken('MyApp')-> accessToken; 
            return response()->json(['success' => $success], $this-> successStatus); 
        } 
        else{ 
            return response()->json(['error'=>'Unauthorised'], 401); 
        } 
    }
	
	/** 
     * Register api 
     * 
     * @return \Illuminate\Http\Response 
     */ 
    public function register(Request $request) 
    { 
        $validator = Validator::make($request->all(), [ 
            'name' => 'required|max:191', 
            'email' => 'required|email|unique:users|max:191', 
            'password' => 'required|max:20|min:6', 
        ]);

		
        if ($validator->fails()) { 
                return response()->json(['error'=>$validator->errors()], 401);            
        }
        
        $input = $request->all(); 
        $input['password'] = Hash::make($input['password']); 
        $input['user_type'] = 'user';
        $input['status'] = 1;
        $input['profile_picture'] = 'default.png';
        $input['currency'] = '$';
        
        $trial_period = get_option('trial_period',7);

        if($trial_period < 1){
        $valid_to = date('Y-m-d', strtotime(date('Y-m-d'). " -1 day"));
        }else{
        $valid_to = date('Y-m-d', strtotime(date('Y-m-d'). " + $trial_period days"));
        }
        $input['valid_to'] = $valid_to;
        
        $user = User::create($input); 
        
        $success['token'] =  $user->createToken('MyApp')->accessToken; 
        $success['name'] =  $user->name;

        return response()->json(['success'=>$success], $this->successStatus); 
			
	}
	
	/** 
     * details api 
     * 
     * @return \Illuminate\Http\Response 
     */ 
    public function details() 
    { 
        $user = Auth::user(); 
        return response()->json(['success' => $user], $this->successStatus); 
    } 
}

resources/views/backend/user/create.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
	<div class="col-md-12">
	<div class="panel panel-default">
	<div class="panel-heading">{{ _lang('Add User') }}</div>

	<div class="panel-body">
		<form method="post" class="validate" autocomplete="off" action="{{url('users')}}" enctype="multipart/form-data">
		    <div class="col-md-6">
				{{ csrf_field() }}
				
				<div class="col-md-12">
				  <div class="form-group">
					<label class="control-label">{{ _lang('Name') }}</label>						
					<input type="text" class="form-control" name="name" value="{{ old('name') }}" required>
				  </div>
				</div>

				<div class="col-md-12">
				  <div class="form-group">
					<label class="control-label">{{ _lang('Email') }}</label>						
					<input type="email" class="form-control" name="email" value="{{ old('email') }}" required>
				  </div>
				</div>

				<div class="col-md-12">
				  <div class="form-group">
					<label class="control-label">{{ _lang('Password') }}</label>						
					<input type="password" class="form-control" name="password" value="{{ old('password') }}" required>
				  </div>
				</div>
				
				<div class="col-md-12">
				 <div class="form-group">
					<label class="control-label">{{ _lang('Confirm Password') }}</label>						
					<input type="password" class="form-control" name="password_confirmation" required>
				 </div>
				</div>

				<div class="col-md-12">
				  <div class="form-group">
					<label class="control-label">{{ _lang('User Type') }}</label>						
					<select class="form-control select2" id="user-type" name="user_type" required>
					  <option value="user">{{ _lang('User') }}</option>
					  <option value="admin">{{ _lang('Admin') }}</option>
					</select>
				  </div>
				</div>
				
				<div class="col-md-12">
				  <div class="form-group">
					<label class="control-label">{{ _lang('Status') }}</label>						
					<select class="form-control select2" id="status" name="status" required>
					  <option value="1">{{ _lang('Active') }}</option>
					  <option value="0">{{ _lang('Inactive') }}</option>
					</select>
				  </div>
				</div>
				
				
				<div class="col-md-12">
				  <div class="form-group">
					<label class="control-label">{{ _lang('Valid To') }}</label>						
					<div class="input-group date">
						<input type="text" class="form-control datepicker" name="valid_to" value="{{ old('valid_to') }}"> 
						<span class="input-group-addon">
							<span class="glyphicon glyphicon-calendar"></span>
						</span>
					</div>
				  </div>
				</div>
				
				<div class="form-group">
				  <div class="col-md-12">
					<button type="reset" class="btn btn-danger">{{ _lang('Reset') }}</button>
					<button type="submit" class="btn btn-primary">{{ _lang('Save') }}</button>
				  </div>
				</div>
				
			</div>
			
			<div class="col-md-6">		
				<div class="col-md-12">
				 <div class="form-group">
					<label class="control-label">{{ _lang('Profile Picture') }} ( 300 X 300 {{ _lang('for better view') }} )</label>						
					<input type="file" class="dropify" name="profile_picture" data-allowed-file-extensions="png jpg jpeg PNG JPG JPEG" data-default-file="">
				 </div>
				</div>
			</div>	
		  </form>
	  
	</div>
  </div>
 </div>
</div>
@endsection

@section('js-script')
<script>
$("#user_type").val("{{ old('user_type') }}");
</script>
@endsection

resources/views/backend/user/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">{{ _lang('Update User') }}</div>

			<div class="panel-body">
			<form method="post" class="validate" autocomplete="off" action="{{action('UserController@update', $id)}}" enctype="multipart/form-data">
				<div class="col-md-6">
					{{ csrf_field()}}
					<input name="_method" type="hidden" value="PATCH">				
					
					<div class="col-md-12">
					 <div class="form-group">
						<label class="control-label">{{ _lang('Name') }}</label>						
						<input type="text" class="form-control" name="name" value="{{ $user->name }}" required>
					 </div>
					</div>

					<div class="col-md-12">
					 <div class="form-group">
						<label class="control-label">{{ _lang('Email') }}</label>						
						<input type="email" class="form-control" name="email" value="{{ $user->email }}" required>
					 </div>
					</div>

					<div class="col-md-12">
					 <div class="form-group">
						<label class="control-label">{{ _lang('Password') }}</label>						
						<input type="password" class="form-control" name="password" value="">
					 </div>
					</div>
					
					<div class="col-md-12">
					 <div class="form-group">
						<label class="control-label">{{ _lang('Confirm Password') }}</label>						
						<input type="password" class="form-control" name="password_confirmation" value="">
					 </div>
					</div>

					<div class="col-md-12">
					  <div class="form-group">
						<label class="control-label">{{ _lang('User Type') }}</label>						
						<select class="form-control select2" name="user_type" id="user_type" required>
						  <option value="user">{{ _lang('User') }}</option>
						  <option value="admin">{{ _lang('Admin') }}</option>
						</select>
					  </div>
					</div>
					
					<div class="col-md-12">
					  <div class="form-group">
						<label class="control-label">{{ _lang('Status') }}</label>						
						<select class="form-control select2" id="status" name="status" required>
						  <option value="1">{{ _lang('Active') }}</option>
						  <option value="0">{{ _lang('Inactive') }}</option>
						</select>
					  </div>
					</div>
					
					<div class="col-md-12">
					  <div class="form-group">
						<label class="control-label">{{ _lang('Valid To') }}</label>						
						<div class="input-group date">
							<input type="text" class="form-control datepicker" name="valid_to" value="{{ $user->valid_to }}">
							<span class="input-group-addon">
								<span class="glyphicon glyphicon-calendar"></span>
							</span>
						</div>
					  </div>
					</div>
					
					<div class="form-group">
					  <div class="col-md-12">
						<button type="submit" class="btn btn-primary">{{ _lang('Update') }}</button>
					  </div>
					</div>
				</div>
				
				<div class="col-md-6">
					<div class="col-md-12">
					 <div class="form-group">
						<label class="control-label">{{ _lang('Profile Picture') }} ( 300 X 300 {{ _lang('for better view') }} )</label>						
						<input type="file" class="dropify" name="profile_picture" data-allowed-file-extensions="png jpg jpeg PNG JPG JPEG" data-default-file="{{ $user->profile_picture != "" ? asset('public/uploads/profile/'.$user->profile_picture) : '' }}" >
					 </div>
					</div>
                </div>

			</form>
			</div>
		</div>
	</div>
</div>

@endsection

@section('js-script')
<script>
$("#user_type").val("{{ $user->user_type }}");
$("#status").val("{{ $user->status }}");
</script>
@endsection

resources/views/backend/user/list.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default no-export">
			<div class="panel-heading"><span class="panel-title">{{ _lang('User List') }}</span>
			<a class="btn btn-primary btn-sm pull-right ajax-modal" data-title="{{ _lang('Add User') }}" href="{{route('users.create')}}">{{ _lang('Add New') }}</a>
			</div>

			<div class="panel-body">
			<table class="table table-bordered data-table">
			<thead>
			  <tr>
				<th class="text-center">{{ _lang('#') }}</th>
				<th>{{ _lang('Name') }}</th>
				<th>{{ _lang('Email') }}</th>
				<th>{{ _lang('User Type') }}</th>
				<th>{{ _lang('Status') }}</th>
				<th class="text-center">{{ _lang('Action') }}</th>
			  </tr>
			</thead>
			<tbody>
			  
			  @foreach($users as $user)
			    <tr id="row_{{ $user->id }}">
					<td class="text-center"><img src="{{ asset('public/uploads/profile/'.$user->profile_picture) }}" class="img-avatar"></td>
					<td class='name'>{{ $user->name }}</td>
					<td class='email'>{{ $user->email }}</td>
					<td class='user_type'>{{ ucwords($user->user_type) }}</td>					
					<td class='status'>{{ $user->status == 1 ? _lang('Active') : _lang('In-Active') }}</td>					
					<td class="text-center">
					  <form action="{{action('UserController@destroy', $user['id'])}}" method="post">
						<a href="{{action('UserController@edit', $user['id'])}}" data-title="{{ _lang('Update User') }}" class="btn btn-warning btn-sm ajax-modal">{{ _lang('Edit') }}</a>
						<a href="{{action('UserController@show', $user['id'])}}" data-title="{{ _lang('View User') }}" class="btn btn-info btn-sm ajax-modal">{{ _lang('View') }}</a>
						{{ csrf_field() }}
						<input name="_method" type="hidden" value="DELETE">
						<button class="btn btn-danger btn-sm btn-remove" type="submit">{{ _lang('Delete') }}</button>
					  </form>
					</td>
			    </tr>
			  @endforeach
			</tbody>
		  </table>
			</div>
		</div>
	</div>
</div>

@endsection

resources/views/backend/user/payments.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default no-export">
			<div class="panel-heading"><span class="panel-title">{{ _lang('Payment History') }}</span></div>

			<div class="panel-body">
			  <table class="table table-bordered data-table">
				<thead>
				  <tr>
					<th>{{ _lang('Date') }}</th>
					<th>{{ _lang('Name') }}</th>
					<th>{{ _lang('Email') }}</th>
					<th>{{ _lang('Details') }}</th>
					<th>{{ _lang('Method') }}</th>
					<th class="text-right">{{ _lang('Amount') }}</th>
				  </tr>
				</thead>
				<tbody>
				  @php $currency = get_option('currency','USD'); @endphp
				  @foreach($payment_history as $history)
					<tr>
						<td>{{ date('d M, Y',strtotime($history->created_at)) }}</td>
						<td>{{ isset($history->user->name)? $history->user->name : '' }}</td>
						<td>{{ isset($history->user->email) ? $history->user->email : '' }}</td>
						<td>{{ $history->title }}</td>
						<td>{{ $history->method }}</td>					
						<td class="text-right">{{ $currency.' '.$history->amount }}</td>					
					</tr>
				  @endforeach
				</tbody>
			  </table>
			  
			  <div class="pull-right">
				 {{ $payment_history->links() }}
			  </div>
			</div>
		</div>
	</div>
</div>

@endsection

resources/views/backend/user/view.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
	<div class="col-md-12">
	<div class="panel panel-default">
	<div class="panel-heading">{{ _lang('View User') }}</div>

	<div class="panel-body">
	  <table class="table table-bordered">
		<tr><td colspan="2"><img style="margin: auto;" class="thumb-image-md thumbnail" src="{{ $user->profile_picture != "" ? asset('public/uploads/profile/'.$user->profile_picture) : asset('public/images/avatar.png') }}"></td></tr>
		<tr><td>{{ _lang('Name') }}</td><td>{{ $user->name }}</td></tr>
		<tr><td>{{ _lang('Email') }}</td><td>{{ $user->email }}</td></tr>
		<tr><td>{{ _lang('User Type') }}</td><td>{{ $user->user_type }}</td></tr>	
	    @if($user->user_type == 'user')
			<tr><td>{{ _lang('Membersip Valid To') }}</td><td>{{ date('d/M/Y',strtotime($user->valid_to)) }}</td></tr>	
	    @endif
	  </table>
	</div>
  </div>
 </div>
</div>
@endsection